#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C
if [[ $# -ne 3 ]]; then
  echo 'Usage: compare-analysis.sh <before-native-binary> <after-native-binary> <new-report-directory>' >&2
  exit 2
fi
before="$(realpath "$1")"
after="$(realpath "$2")"
test -x "$before"
test -x "$after"
report="$3"
[[ ! -e "$report" ]] || { echo 'Choose a fresh report directory' >&2; exit 1; }
mkdir -p "$report"
report="$(realpath "$report")"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/site/content" "$tmp/site/public"
printf '<title>{{title}}</title>{{toc}}<main>{{content}}</main>' > "$tmp/site/layout.html"
printf 'body {}' > "$tmp/site/style.css"
printf '<svg/>' > "$tmp/site/public/image.svg"
for ((page=1; page<=100; page++)); do
  next=$((page % 100 + 1))
  {
    printf '%s\n' '---' '{"tags":["core"]}' '---'
    printf '# Page %s\n\n' "$page"
    for ((section=1; section<=24; section++)); do
      printf '## Section %s\n\n[Next](page-%s.html#mp-section-%s) ![Image](image.svg)\n\n' "$section" "$next" "$section"
      printf '%s\n' '- List `literal [ignored](ghost.html)`' '> Quoted text' '' '~~~' '# Not a heading' '[ignored](ghost.html#mp-missing)' '~~~' ''
    done
  } > "$tmp/site/content/page-$page.md"
done
printf 'repeat,variant,scenario,microseconds\n' > "$report/raw.csv"
measure() {
  local variant="$1" scenario="$2" start end
  shift 2
  start="${EPOCHREALTIME/./}"
  "$@" > "$tmp/$variant.$scenario.json"
  end="${EPOCHREALTIME/./}"
  printf '%s,%s,%s,%s\n' "$repeat" "$variant" "$scenario" "$((end-start))" >> "$report/raw.csv"
}
for ((repeat=1; repeat<=5; repeat++)); do
  order=(before after)
  if ((repeat % 2 == 0)); then order=(after before); fi
  for variant in "${order[@]}"; do
    binary="$before"
    if [[ "$variant" == after ]]; then binary="$after"; fi
    measure "$variant" check "$binary" check "$tmp/site" --json
    measure "$variant" clean "$binary" build "$tmp/site" "$tmp/$variant-$repeat" --json
    measure "$variant" noop "$binary" build "$tmp/site" "$tmp/$variant-$repeat" --json
  done
  for scenario in check clean noop; do cmp "$tmp/before.$scenario.json" "$tmp/after.$scenario.json"; done
  diff -r "$tmp/before-$repeat" "$tmp/after-$repeat"
done
{
  echo '# Shared Markdown analysis comparison'
  echo
  printf -- '- UTC: %s\n' "$(date -u +%FT%TZ)"
  printf -- '- Host: %s\n' "$(uname -srm)"
  printf -- '- CPU: %s\n' "$(lscpu | awk -F: '/Model name/{sub(/^ +/,"",$2);print $2;exit}')"
  printf -- '- Before source: %s\n' "${BEFORE_REVISION:-unspecified}"
  printf -- '- After source: %s\n' "${AFTER_REVISION:-working tree for this change}"
  printf -- '- Before executable SHA-256: %s\n' "$(sha256sum "$before" | cut -d' ' -f1)"
  printf -- '- After executable SHA-256: %s\n' "$(sha256sum "$after" | cut -d' ' -f1)"
  printf -- '- Native bytes before / after: %s / %s\n' "$(wc -c < "$before")" "$(wc -c < "$after")"
  printf -- '- Toolchain: %s; %s\n' "$(moon version | head -1)" "$(moonc -v)"
  echo
  echo '| Variant | Scenario | Mean ms | Min ms | Max ms |'
  echo '| --- | --- | ---: | ---: | ---: |'
  awk -F, 'NR>1{k=$2 SUBSEP $3;n[k]++;s[k]+=$4;if(n[k]==1||$4<lo[k])lo[k]=$4;if($4>hi[k])hi[k]=$4} END{for(k in n){split(k,a,SUBSEP);printf "| %s | %s | %.3f | %.3f | %.3f |\n",a[1],a[2],s[k]/n[k]/1000,lo[k]/1000,hi[k]/1000}}' "$report/raw.csv" | sort
  echo
  echo 'Fixture: 100 pages, 24 sections per page, cross-page heading links, images, lists, quotes, inline/fenced code, a TOC and a tag collection. Five paired repetitions alternate executable order. Every pair compares all generated bytes (including manifests) and JSON reports for check, clean and no-op.'
  echo
  echo 'Timing: Bash EPOCHREALTIME wall time includes native process startup and filesystem I/O. Caches are not flushed; fresh output does not mean cold OS cache. Microsecond units do not establish that precision. This single-host synthetic comparison is not a general speed guarantee or a comparison to another SSG. Raw samples are retained in raw.csv; no memory-usage claim is made.'
  echo
  echo 'Reproduce: build both revisions with the verified native release toolchain, keep their executables separately, then run `bash scripts/compare-analysis.sh /path/to/before /path/to/after /path/to/new-report-directory`. Set BEFORE_REVISION and AFTER_REVISION to identify the inputs.'
} > "$report/report.md"
cat "$report/report.md"
